### Base Objects
Chiller:
  Electric:
    EIR:
      Base: &ChillerElectricEIRComponents
        Chiller:Electric:EIR:
          Fields:
            name: '{} Chiller'
            chilled_water_inlet_node_name: '{} Chiller ChW Inlet'
            chilled_water_outlet_node_name: '{} Chiller ChW Outlet'
            total_cooling_capacity_function_of_temperature_curve_name: Main Chiller RecipCapFT
          Connectors:
            ChilledWaterLoop:
              Inlet: chilled_water_inlet_node_name
              Outlet: chilled_water_outlet_node_name
        Pipe:Adiabatic:
          Fields:
            name: '{} Demand Side Bypass Pipe'
            inlet_node_name: '{} Demand Bypass Inlet'
            outlet_node_name: '{} Demand Bypass Outlet'
          Connectors:
            ChilledWaterLoop:
              Inlet: inlet_node_name
              Outlet: outlet_node_name
              UseInBuildPath: false #Necessary for all parallel objects

Coil:
  Cooling:
    Water:
      Fields: &CoilCoolingFields
        name: '{} Cooling Coil'
        air_inlet_node_name: '{} Cooling Coil Inlet'
        air_outlet_node_name: '{} Cooling Coil Outlet'
        water_inlet_node_name: '{} Cooling Coil Chw Inlet'
        water_outlet_node_name: '{} Cooling Coil Chw Outlet'
      Connectors: &CoilCoolingConnectors
        Air:
          Inlet: air_inlet_node_name
          Outlet: air_outlet_node_name
        ChilledWaterLoop:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilCoolingWater
        Fields:
          << : *CoilCoolingFields
        Connectors:
          << : *CoilCoolingConnectors
      DetailedGeometry:
        Fields:
          << : *CoilCoolingFields
        Connectors:
          << : *CoilCoolingConnectors
  Heating:
    Fields: &CoilHeatingFields
      name: '{} Heating Coil'
      air_inlet_node_name: '{} Heating Coil Inlet'
      air_outlet_node_name: '{} Heating Coil Outlet'
    Connectors: &CoilHeatingConnectors
      Air:
        Inlet: air_inlet_node_name
        Outlet: air_outlet_node_name
    Electric:
      Fields:
      Connectors:
      Base: &CoilHeatingElectric
        Fields:
          <<: *CoilHeatingFields
        Connectors:
          <<: *CoilHeatingConnectors
    Water:
      Fields: &CoilHeatingWaterFields
        << : *CoilHeatingFields
        water_inlet_node_name: '{} Heating Coil Hw Inlet'
        water_outlet_node_name: '{} Heating Coil Hw Outlet'
      Connectors: &CoilHeatingWaterConnectors
        << : *CoilHeatingConnectors
        HotWaterLoop:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilHeatingWater
        Fields:
          <<: *CoilHeatingWaterFields
        Connectors:
          <<: *CoilHeatingWaterConnectors

CoolingTower:
  SingleSpeed:
    Base: &CoolingTowerSingleSpeed
      Fields:
        name: '{} Tower'
        water_inlet_node_name: '{} CndW Inlet'
        water_outlet_node_name: '{} CndW Outlet'
      Connectors:
        CondenserWaterLoop:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name

Fan:
  Fields: &FanFields # example of default inputs, but i'm not sure if it's necessary.
    motor_efficiency: 0.9
    maximum_flow_rate: Autosize
  Connectors: &FanConnectors
    Air:
      Inlet: air_inlet_node_name
      Outlet: air_outlet_node_name
  VariableVolume:
    Base: &FanVariableVolume
      Fields:
        name: '{} Supply Fan'
        << : *FanFields
        fan_power_minimum_flow_fraction: 0.25
        air_inlet_node_name: '{} Supply Fan Inlet'
        air_outlet_node_name: '{} Supply Fan Outlet'
      Connectors:
        << : *FanConnectors

OutdoorAir:Mixer: # structure might be unnecessary but is being used for example
  Fields: &OutdoorAirMixerFields
    name: '{} OA Mixing Box'
    mixed_air_node_name: '{} Mixed Air Outlet'
    outdoor_air_stream_node_name: '{} Outside Air Inlet' #will be overridden
    relief_air_stream_node_name: '{} Relief Air Outlet'
    return_air_stream_node_name: '{} Return Air Loop Inlet'
  Connectors: &OutdoorAirMixersConnectors
    Air:
      Inlet: outdoor_air_stream_node_name
      Outlet: mixed_air_node_name
  Base:
    OutdoorAir:Mixer: &OutdoorAirMixer
      Fields:
        << : *OutdoorAirMixerFields
      Connectors:
        << : *OutdoorAirMixersConnectors

Pipe:
  Adiabatic:
    Base:
      Pipe:Adiabatic:
        Fields:
          name: '{} Pipe'
          inlet_node_name: '{} Pipe Inlet'
          outlet_node_name: '{} Pipe Outlet'
        Connectors: &PipeAdiabaticConnectors
          ChilledWaterLoop:
            Inlet: inlet_node_name
            Outlet: outlet_node_name
          CondenserWaterLoop:
            Inlet: inlet_node_name
            Outlet: outlet_node_name
          HotWaterLoop:
            Inlet: inlet_node_name
            Outlet: outlet_node_name
    SuppyInlet: &PipeAdiabaticSupplyInlet
      Pipe:Adiabatic:
        Fields:
          name: '{} Demand Inlet Pipe'
          inlet_node_name: '{} Demand Inlet'
          outlet_node_name: '{} Demand Inlet Pipe Outlet'
        Connectors:
          <<: *PipeAdiabaticConnectors
    SupplyOutlet: &PipeAdiabaticSupplyOutlet
      Pipe:Adiabatic:
        Fields:
          name: '{} Demand Outlet Pipe'
          inlet_node_name: '{} Demand Outlet Pipe Inlet'
          outlet_node_name: '{} Demand Outlet'
        Connectors:
          <<: *PipeAdiabaticConnectors

Pump:
  ConstantSpeed: &PumpConstantSpeed
    Fields:
      name: '{} Supply Pump'
      inlet_node_name: '{} Pump Inlet'
      outlet_node_name: '{} Pump Outlet'
    Connectors:
      ChilledWaterLoop:
        Inlet: inlet_node_name
        Outlet: outlet_node_name
      HotWaterLoop:
        Inlet: inlet_node_name
        Outlet: outlet_node_name
      CondenserWaterLoop:
        Inlet: inlet_node_name
        Outlet: outlet_node_name

### Complex Objects
AirTerminal:
  SingleDuct:
    Fields: &AirTerminalSingleDuctFields
      maximum_air_flow_rate: 'Autosize'
      damper_air_outlet_node_name: '{} Damper Outlet'
      air_inlet_node_name: '{} Zone Equip Inlet'
      air_outlet_node_name: '{} Supply Inlet'
    Connectors:
      Air: &AirTerminalSingleDuctConnectorsAir
        Inlet: air_inlet_node_name
        Outlet: air_outlet_node_name
      Water: &AirTerminalSingleDuctConnectorsWater
        Inlet: water_inlet_node_name
        Outlet: water_outlet_node_name
    VAV:
      Reheat:
        Base: &AirTerminalSingleDuctVAVReheat
          AirTerminal:SingleDuct:VAV:Reheat:
            Fields:
              name: '{} VAV Reheat'
              <<: *AirTerminalSingleDuctFields
            Connectors:
              Air: *AirTerminalSingleDuctConnectorsAir
          Coil:Heating:Water:
            Fields:
              <<: *CoilHeatingWaterFields
              air_inlet_node_name: '{} Damper Outlet' # keys can be overridden like this
              air_outlet_node_name: '{} Supply Inlet'
            Connectors:
              Air: *AirTerminalSingleDuctConnectorsAir
              HotWaterLoop:
                <<: *AirTerminalSingleDuctConnectorsWater
                UseInBuildPath: false
      NoReheat:
        Base: &AirTerminalSingleDuctVAVNoReheat
          Fields:
            name: '{} VAV'
            <<: *AirTerminalSingleDuctFields
          Connectors:
            Air: *AirTerminalSingleDuctConnectorsAir

### Additional Equipment
Controller:
  OutdoorAir:
    Base:
      Controller:OutdoorAir: &ControllerOutdoorAir
        name: '{} OA Controller'
        relief_air_outlet_node_name:
          OutdoorAir:M.*: relief_air_stream_node_name
        #          Occurrence: 1
        return_air_node_name:
          OutdoorAir:Mixer: return_air_stream_node_name

DesignSpecification:
  OutdoorAir:
    Base: &DesignSpecificationOutdoorAir
      name: '{} SZ DSOA'
  ZoneAirDistribution:
    Base: &DesignSpecificationZoneAirDistribution
      name: '{} SZ DSZAD'
      zone_air_distribution_effectiveness_in_cooling_mode: 1
      zone_air_distribution_effectiveness_in_heating_mode: 1


OutdoorAir:NodeList:
  Base:
    OutdoorAir:NodeList:
      Fields:
        - '{} Outside Air Inlet'
      Connectors:
        Air:
          Outlet: '{} Outside Air Inlet'

Schedule:
  Compact:
    ALWAYS_VAL:
      name: 'ALWAYS_{}'
      data:
        - Through 12/31
        - For AllDays
        - Until 24:00
        - '{:.1f}'

SetpointManagers:
  MixedAir:
    Base:
      SetpointManager:MixedAir: &SetpointManagerMixedAir
        name: '{} Cooling Coil Air Temp Manager'
        control_variable: Temperature
        reference_setpoint_node_name:
          Fan:VariableVolume: air_outlet_node_name
        fan_inlet_node_name:
          Fan:VariableVolume: air_inlet_node_name
        fan_outlet_node_name:
          Fan:VariableVolume: air_outlet_node_name
        setpoint_node_or_nodelist_name: '{} Mixed Air Nodes'

ZoneControl:
  Thermostat:
    Base: &ZoneControlThermostat
      name: '{} Thermostat'

ZoneHVAC:
  AirDistributionUnit:
    Base: &ZoneHVACAirDistributionUnit
      name: '{} ATU'
      air_distribution_unit_outlet_node_name:
        ^AirTerminal:.*: air_outlet_node_name
      air_terminal_object_type:
        ^AirTerminal:.*: self
      air_terminal_name:
        ^AirTerminal:.*: key

### Common Combinations
SystemConfigOutdoorAirBase: &SystemConfigOutdoorAirBase
  - OutdoorAir:Mixer: *OutdoorAirMixer
  - Coil:Cooling:Water: *CoilCoolingWater
  - Coil:Heating:Water: *CoilHeatingWater
  - Fan:VariableVolume: *FanVariableVolume

### HVAC System Templates
HVACTemplate:
  Zone:
    VAV: &HVACTemplateZoneVAV
      BuildPath:
        - *AirTerminalSingleDuctVAVReheat
      Transitions:
        supply_air_maximum_flow_rate:
          AirTerminal:.*: 'autosize'
      Connectors:
        Supply:
        Demand:
  System:
    VAV: &HVACTemplateSystemVAV
      BuildPath: # path of airflow through components
        - *SystemConfigOutdoorAirBase
      Transitions: # values to transition from template to child objects {object_type: object_field_name}
        supply_fan_total_efficiency:
          Fan:.*: fan_total_efficiency
      Connectors: # define system level connections
        Supply: # we can easily get the outlet name from the last object in the buildPath so it's not referenced here
          Inlet:
            OutdoorAir:Mixer: return_air_stream_node_name
        Demand:
          Inlet: '{} Supply Path Inlet'
          Outlet: '{} Return Air Outlet'
  Plant:
    Chiller: &HVACTemplatePlantChiller
      BuildPath:
        - <<: *ChillerElectricEIRComponents
      Transitions:
        capacity:
          ^Chiller:.*: reference_capacity
    ChilledWaterLoop: &HVACTemplatePlantChilledWaterLoop
      BuildPath:
        - Pump:ConstantSpeed: *PumpConstantSpeed
        - HVACTemplate:Plant:Chiller # specify a nested template with a text reference to the object under the OptionTree object
        - <<: *PipeAdiabaticSupplyOutlet
    CondenserWaterLoop: &HVACTemplatePlantCondenserWaterLoop
      BuildPath:
        - <<: *PipeAdiabaticSupplyInlet
        - HVACTemplate:Plant:Tower
        - <<: *PipeAdiabaticSupplyOutlet
    Tower: &HVACTemplatePlantTower
      BuildPath:
        - CoolingTower:SingleSpeed: *CoolingTowerSingleSpeed

### Option Trees
OptionTree:
  HVACTemplate:
    Zone:
      VAV:
        Base: *HVACTemplateZoneVAV
#        RemoveElements:
#          reheat_coil_type:
#            HotWaterLoop:
#              ^Coil:Heating:.*:
#                Object: _ # necessary to preserve same structure as other actions
        ReplaceElements:
          reheat_coil_type:
            None:
              '^AirTerminal:.*':
                Object:
                  AirTerminal:SingleDuct:VAV:NoReheat: *AirTerminalSingleDuctVAVNoReheat
            Electric:
              ^Coil:Heating.*:
                Object:
                  Coil:Heating:Electric:
                    Fields:
                      <<: *CoilHeatingFields
                      air_inlet_node_name: '{} Damper Outlet'
                      air_outlet_node_name: '{} Supply Inlet'
                    Connectors:
                      Air:
                        Inlet: '{} Damper Outlet'
                        Outlet: '{} Supply Inlet'
            Gas:
              ^Coil:Heating.*:
                Object:
                  Coil:Heating:Fuel:
                    Fields:
                      <<: *CoilHeatingFields
                      air_inlet_node_name: '{} Damper Outlet'
                      air_outlet_node_name: '{} Supply Inlet'
                    Connectors:
                      Air:
                        Inlet: '{} Damper Outlet'
                        Outlet: '{} Supply Inlet'
        InsertElements:
        AdditionalObjects:
          ZoneHVAC:AirDistributionUnit: *ZoneHVACAirDistributionUnit
          ZoneControl:Thermostat:
            <<: *ZoneControlThermostat
            Transitions:
              zone_name: zone_or_zone_list_name
              template_thermostat_name: control_1_name
        AdditionalTemplateObjects:
          outdoor_air_method: # This group should be created in an anchor for re-use
            Flow/Per.*: # can be regex
              DesignSpecification:OutdoorAir: # aliases can be mapped using <<: *var to add more key/values to that level of dictionary.
                <<: *DesignSpecificationOutdoorAir
                Transitions:
                  outdoor_air_method: outdoor_air_method
                  outdoor_air_flow_rate_per_person: outdoor_air_flow_per_person
              DesignSpecificationZoneAirDistribution: *DesignSpecificationZoneAirDistribution #Aliases are added this way typically
            Flow/Area:
              DesignSpecification:OutdoorAir: # aliases can be mapped using <<: *var to add more key/values to that level of dictionary.
                <<: *DesignSpecificationOutdoorAir
                Transitions:
                  outdoor_air_method: outdoor_air_method
                  outdoor_air_flow_rate_per_zone_floor_area: outdoor_air_flow_per_zone_floor_area
                DesignSpecificationZoneAirDistribution: *DesignSpecificationZoneAirDistribution #Aliases are added this way typically
            Flow/Zone:
              DesignSpecification:OutdoorAir: # aliases can be mapped using <<: *var to add more key/values to that level of dictionary.
                <<: *DesignSpecificationOutdoorAir
                Transitions:
                  outdoor_air_method: outdoor_air_method
                  outdoor_air_flow_rate_per_zone: outdoor_air_flow_per_zone
                DesignSpecificationZoneAirDistribution: *DesignSpecificationZoneAirDistribution #Aliases are added this way typically
            Sum:
              DesignSpecification:OutdoorAir: # aliases can be mapped using <<: *var to add more key/values to that level of dictionary.
                <<: *DesignSpecificationOutdoorAir
                Transitions:
                  outdoor_air_method: outdoor_air_method
                  outdoor_air_flow_rate_per_person: outdoor_air_flow_per_person
                  outdoor_air_flow_rate_per_zone_floor_area: outdoor_air_flow_per_zone_floor_area
                  outdoor_air_flow_rate_per_zone: outdoor_air_flow_per_zone
                DesignSpecificationZoneAirDistribution: *DesignSpecificationZoneAirDistribution #Aliases are added this way typically
            Max:
              DesignSpecification:OutdoorAir: # aliases can be mapped using <<: *var to add more key/values to that level of dictionary.
                <<: *DesignSpecificationOutdoorAir
                Transitions:
                  outdoor_air_method: outdoor_air_method
                  outdoor_air_flow_rate_per_person: outdoor_air_flow_per_person
                  outdoor_air_flow_rate_per_zone_floor_area: outdoor_air_flow_per_zone_floor_area
                  outdoor_air_flow_rate_per_zone: outdoor_air_flow_per_zone
                DesignSpecificationZoneAirDistribution: *DesignSpecificationZoneAirDistribution #Aliases are added this way typically
    System:
      VAV: # configuration to store options for altering a base build
        Base: *HVACTemplateSystemVAV
        RemoveElements: # Not sure if this is needed but it should be possible, probably using list.pop()
        ReplaceElements: # replace an existing element with something else
          heating_coil_type: # base path must have an object to replace for this to work
            None: None
            Electric:
              ^Coil:Heating:.*:
                Occurrence: 1
                Object:
                  Coil:Heating:Electric: *CoilHeatingElectric # anchor/map reference to coil
                FieldNameReplacement: '{} Electric'
        InsertElements: # Insert element before or after another element
          preheat_coil_type:
            Electric:
              OutdoorAir:M.*:
                Location: Before
                Occurrence: 1
                Object:
                  Coil:Heating:Electric: *CoilHeatingElectric
                FieldNameReplacement: '{} Preheat Electric'
                Transitions: # transition template variable to this specific inserted object {template_field_name: object_field_name}
                  preheat_efficiency: efficiency # doesn't currently exist as an option, this is just an example. Use '.*' because it references only the current object.
        AdditionalObjects: # nested hvac template in AdditionalObjects.
#          HVACTemplate:Plant:CondenserWaterLoop: # just an example, doesn't make sense here
#            ConnectorPath: CondenserWaterLoop
#            UniqueName: 'Main CndW'  #Value is the unique name modifier
          SetpointManager:MixedAir:
            <<: *SetpointManagerMixedAir
#            sample_additional_field: sample_transition_value
          Controller:OutdoorAir:
            <<: *ControllerOutdoorAir
        AdditionalTemplateObjects: # template triggered objects
#          template_field:
#            template_choice:
#              object_groups:
    Plant:
      Chiller:
        Base: *HVACTemplatePlantChiller
        ReplaceElements:
        AdditionalTemplateObjects:
          condenser_type:
            WaterCooled:
              HVACTemplate:Plant:CondenserWaterLoop:
                ConnectorPath: CondenserWaterLoop
                UniqueName: 'Main CndW'
      ChilledWaterLoop:
        Base: *HVACTemplatePlantChilledWaterLoop
      CondenserWaterLoop:
        Base: *HVACTemplatePlantCondenserWaterLoop
      Tower:
        Base: *HVACTemplatePlantTower
        AdditionalObjects: # Work on this
          Branch:
            name: '{}'
            type:
              CoolingTower.*: self
