# Base Objects
OutdoorAir:NodeList:
  Base:
    OutdoorAir:NodeList:
      Fields:
        - '{} Outside Air Inlet'
      Connectors:
        Air:
          Outlet: '{} Outside Air Inlet'

OutdoorAir:Mixer: # structure might be unnecessary but is being used for example
  Fields: &OutdoorAirMixerFields
    name: '{} OA Mixing Box'
    mixed_air_node_name: '{} Mixed Air Outlet'
    outdoor_air_stream_node_name: '{} Outside Air Inlet' #will be overridden
    relief_air_stream_node_name: '{} Relief Air Outlet'
    return_air_stream_node_name: '{} Return Air Loop Inlet'
  Connectors: &OutdoorAirMixersConnectors
    Air:
      Inlet: outdoor_air_stream_node_name
      Outlet: mixed_air_node_name
  Base: &OutdoorAirMixerBase
    OutdoorAir:Mixer:
      Fields:
        << : *OutdoorAirMixerFields
      Connectors:
        << : *OutdoorAirMixersConnectors

Coil:
  Cooling:
    Water:
      Fields: &CoilsCoolingFields
        name: '{} Cooling Coil'
        air_inlet_node_name: '{} Cooling Coil Inlet'
        air_outlet_node_name: '{} Cooling Coil Outlet'
        water_inlet_node_name: '{} Cooling Coil Chw Inlet'
        water_outlet_node_name: '{} Cooling Coil Chw Outlet'
      Connectors: &CoilsCoolingConnectors
        Air:
          Inlet: air_inlet_node_name
          Outlet: air_outlet_node_name
        ChilledWaterLoop:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilsCoolingWaterBase
        Coil:Cooling:Water:
          Fields:
            << : *CoilsCoolingFields
          Connectors:
            << : *CoilsCoolingConnectors
      DetailedGeometry:
        Coil:Cooling:Water:DetailedGeometry:
          Fields:
            << : *CoilsCoolingFields
          Connectors:
            << : *CoilsCoolingConnectors
  Heating:
    Fields: &CoilsHeatingFields
      name: '{} Heating Coil'
      air_inlet_node_name: '{} Heating Coil Inlet'
      air_outlet_node_name: '{} Heating Coil Outlet'
    Connectors: &CoilsHeatingConnectors
      Air:
        Inlet: air_inlet_node_name
        Outlet: air_outlet_node_name
    Electric:
      Fields:
      Connectors:
      Base: &CoilsHeatingElectricBase
        Coil:Heating:Electric:
          Fields:
            <<: *CoilsHeatingFields
          Connectors:
            <<: *CoilsHeatingConnectors
    Water:
      Fields: &CoilsHeatingWaterFields
        << : *CoilsHeatingFields
        water_inlet_node_name: '{} Heating Coil Hw Inlet'
        water_outlet_node_name: '{} Heating Coil Hw Outlet'
      Connectors: &CoilsHeatingWaterConnectors
        << : *CoilsHeatingConnectors
        HotWater:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilsHeatingWaterBase
        Coil:Heating:Water:
          Fields:
            <<: *CoilsHeatingWaterFields
          Connectors:
            <<: *CoilsHeatingWaterConnectors

Fan:
  Fields: &FanFields # example of default inputs, but i'm not sure if it's necessary.
    motor_efficiency: 0.9
    maximum_flow_rate: Autosize
  Connectors: &FanConnectors
    Air:
      Inlet: air_inlet_node_name
      Outlet: air_outlet_node_name
  VariableVolume:
    Base: &FanVariableVolumeBase
      Fan:VariableVolume:
        Fields:
          name: '{} Supply Fan'
          << : *FanFields
          fan_power_minimum_flow_fraction: 0.25
          air_inlet_node_name: '{} Supply Fan Inlet'
          air_outlet_node_name: '{} Supply Fan Outlet'
        Connectors:
          << : *FanConnectors

AirTerminal:
  SingleDuct:
    Fields: &AirTerminalSingleDuctFields
      maximum_air_flow_rate: 'Autosize'
      damper_air_outlet_node_name: '{} Damper Outlet'
      air_inlet_node_name: '{} Zone Equip Inlet'
      air_outlet_node_name: '{} Supply Inlet'
    VAV:
      Reheat:
        Base: &AirTerminalSingleDuctVAVReheat
          AirTerminal:SingleDuct:VAV:Reheat:
            Fields:
              name: '{} VAV Reheat'
              <<: *AirTerminalSingleDuctFields
            Connectors:
              Air:
                Inlet: air_inlet_node_name
                Outlet: air_outlet_node_name
          Coil:Heating:Water:
            Fields:
              <<: *CoilsHeatingWaterFields
              air_inlet_node_name: '{} Damper Outlet' # keys can be overridden like this
              air_outlet_node_name: '{} Supply Inlet'
            Connectors:
              Air:
                Inlet: air_inlet_node_name
                Outlet: air_outlet_node_name
              HotWater:
                Inlet: water_inlet_node_name
                Outlet: water_outlet_node_name
      NoReheat:
        Base: &AirTerminalSingleDuctVAVNoReheat
          AirTerminal:SingleDuct:VAV:NoReheat:
            Fields:
              name: '{} VAV'
              <<: *AirTerminalSingleDuctFields
            Connectors:
              Air:
                Inlet: air_inlet_node_name
                Outlet: air_outlet_node_name

Pipe:
  Adiabatic:
    Base: &PipeAdiabatic
      Pipe:Adiabatic:
        Fields:
          name: '{} Pipe'
          inlet_node_name: '{} Pipe Inlet'
          outlet_node_name: '{} Pipe Outlet'
        Connectors: &PipeAdiabaticConnectors
          ChilledWaterLoop:
            Inlet: inlet_node_name
            Outlet: outlet_node_name
          CondenserWaterLoop:
            Inlet: inlet_node_name
            Outlet: outlet_node_name
    DemandInlet: &PipeAdiabaticDemandInlet
      Pipe:Adiabatic:
        Fields:
          name: '{} Demand Inlet Pipe'
          inlet_node_name: '{} Demand Inlet'
          outlet_node_name: '{} Demand Inlet Pipe Outlet'
        Connectors:
          <<: *PipeAdiabaticConnectors
    DemandOutlet: &PipeAdiabaticDemandOutlet
      Pipe:Adiabatic:
        Fields:
          name: '{} Demand Outlet Pipe'
          inlet_node_name: '{} Demand Outlet Pipe Inlet'
          outlet_node_name: '{} Demand Outlet'
        Connectors:
          <<: *PipeAdiabaticConnectors

Chiller:
  Electric:
    EIR:
      Base: &ChillerElectricEIR
        Chiller:Electric:EIR:
          Fields:
            name: '{} Chiller'
            chilled_water_inlet_node_name: '{} Chiller ChW Inlet'
            chilled_water_outlet_node_name: '{} Chiller ChW Outlet'
            total_cooling_capacity_function_of_temperature_curve_name: Main Chiller RecipCapFT
          Connectors:
            ChilledWaterLoop:
              Inlet: chilled_water_inlet_node_name
              Outlet: chilled_water_outlet_node_name
        Pipe:Adiabatic:
          Fields:
            name: '{} Demand Side Bypass Pipe'
            inlet_node_name: '{} Demand Bypass Inlet'
            outlet_node_name: '{} Demand Bypass Outlet'
          Connectors:
            <<: *PipeAdiabaticConnectors

CoolingTower:
  SingleSpeed:
    Base: &CoolingTowerSingleSpeed
      CoolingTower:SingleSpeed:
        Fields:
          name: '{} Tower'
          water_inlet_node_name: '{} CndW Inlet'
          water_outlet_node_name: '{} CndW Outlet'
        Connectors:
          CondenserWaterLoop:
            Inlet: water_inlet_node_name
            Outlet: water_outlet_node_name


# common sub-system components.  Mostly used to reduce redundant code
SystemConfigOutdoorAirBase: &SystemConfigOutdoorAirBase
  - << : *OutdoorAirMixerBase
  - << : *CoilsCoolingWaterBase
  - << : *CoilsHeatingWaterBase
  - << : *FanVariableVolumeBase

SetpointManagers:
  MixedAir:
    Base:
      SetpointManager:MixedAir: &SetpointManagerMixedAir
        name: '{} Cooling Coil Air Temp Manager'
        control_variable: Temperature
        reference_setpoint_node_name:
          Fan:VariableVolume: air_outlet_node_name
        fan_inlet_node_name:
          Fan:VariableVolume: air_inlet_node_name
        fan_outlet_node_name:
          Fan:VariableVolume: air_outlet_node_name
        setpoint_node_or_nodelist_name: '{} Mixed Air Nodes'

Controller:
  OutdoorAir:
    Base:
      Controller:OutdoorAir: &ControllerOutdoorAir
        name: '{} OA Controller'
        relief_air_outlet_node_name:
          OutdoorAir:M.*: relief_air_stream_node_name
        #          Occurrence: 1
        return_air_node_name:
          OutdoorAir:Mixer: return_air_stream_node_name

# HVAC System Templates
HVACTemplate:
  Zone:
    VAV: &HVACTemplateZoneVAV
      BuildPath:
        - *AirTerminalSingleDuctVAVReheat
      Transition:
        supply_air_maximum_flow_rate:
          AirTerminal:.*: 'autosize'
      Connectors:
        Supply:
        Demand:
  System:
    VAV: &HVACTemplateSystemVAV
      BuildPath: # path of airflow through components
        - *SystemConfigOutdoorAirBase
      Transitions: # values to transition from template to child objects {object_type: object_field_name}
        supply_fan_total_efficiency:
          Fan:.*: fan_total_efficiency
      Connectors: # define system level connections
        Supply: # we can easily get the outlet name from the last object in the buildPath so it's not referenced here
          Inlet:
            OutdoorAir:Mixer: return_air_stream_node_name
        Demand:
          Inlet: '{} Supply Path Inlet'
          Outlet: '{} Return Air Outlet'
  Plant:
    Chiller: &HVACTemplatePlantChiller
      BuildPath:
        - *ChillerElectricEIR
      Transitions:
        capacity:
          ^Chiller:.*: reference_capacity
    ChilledWaterLoop: &HVACTemplatePlantChilledWaterLoop
      BuildPath:
        - <<: *PipeAdiabaticDemandInlet
        - HVACTemplate:Plant:Chiller # specify a nested template with a text reference to the object under the OptionTree object
        - <<: *PipeAdiabaticDemandOutlet
    CondenserWaterLoop: &HVACTemplatePlantCondenserWaterLoop
      BuildPath:
        - <<: *PipeAdiabaticDemandInlet
        - HVACTemplate:Plant:Tower
        - <<: *PipeAdiabaticDemandOutlet
    Tower: &HVACTemplatePlantTower
      BuildPath:
        - *CoolingTowerSingleSpeed

# Miscellaneous
ZoneHVAC:
  AirDistributionUnit:
    Base:
      ZoneHVAC:AirDistributionUnit: &ZoneHVACAirDistributionUnit
        name: '{} ATU'
        air_distribution_unit_outlet_node_name:
          ^AirTerminal:.*: air_outlet_node_name
        air_terminal_object_type:
          ^AirTerminal:.*: self
        air_terminal_name:
          ^AirTerminal:.*: key

# Option trees
OptionTree:
  HVACTemplate:
    Zone:
      VAV:
        Base: *HVACTemplateZoneVAV
#        RemoveElements:
#          reheat_coil_type:
#            HotWater:
#              ^Coil:Heating:.*:
#                Object: _ # necessary to preserve same structure as other actions
        ReplaceElements:
          reheat_coil_type:
            None:
              '^AirTerminal:.*':
                Object:
                  <<: *AirTerminalSingleDuctVAVNoReheat
            Electric:
              ^Coil:Heating.*:
                Object:
                  Coil:Heating:Electric:
                    Fields:
                      <<: *CoilsHeatingFields
                      air_inlet_node_name: '{} Damper Outlet'
                      air_outlet_node_name: '{} Supply Inlet'
                    Connectors:
                      Air:
                        Inlet: '{} Damper Outlet'
                        Outlet: '{} Supply Inlet'
        InsertElements:
        AdditionalObjects:
          ZoneHVAC:AirDistributionUnit:
            <<: *ZoneHVACAirDistributionUnit
        AdditionalTemplateObjects:
    System:
      VAV: # configuration to store options for altering a base build
        Base: *HVACTemplateSystemVAV
        RemoveElements: # Not sure if this is needed but it should be possible, probably using list.pop()
        ReplaceElements: # replace an existing element with something else
          heating_coil_type: # base path must have an object to replace for this to work
            None: None
            Electric:
              ^Coil:Heating:.*:
                Occurrence: 1
                Object: *CoilsHeatingElectricBase # anchor/map reference to coil
                FieldNameReplacement: '{} Electric'
        InsertElements: # Insert element before or after another element
          preheat_coil_type:
            Electric:
              OutdoorAir:M.*:
                Location: Before
                Occurrence: 1
                Object: *CoilsHeatingElectricBase
                FieldNameReplacement: '{} Preheat Electric'
                Transitions: # transition template variable to this specific inserted object {template_field_name: object_field_name}
                  preheat_efficiency:
                    .*: efficiency # doesn't currently exist as an option, this is just an example. Use '.*' because it references only the current object.
        AdditionalObjects: # nested hvac template in AdditionalObjects.
#          HVACTemplate:Plant:CondenserWaterLoop:
#            ConnectorPath: CondenserWaterLoop
#            UniqueName: 'Main CndW'  #Value is the unique name modifier
          SetpointManager:MixedAir:
            <<: *SetpointManagerMixedAir
#            sample_transition_field: sample_transition_value
          Controller:OutdoorAir:
            <<: *ControllerOutdoorAir
        AdditionalTemplateObjects: # template triggered objects
#          template_field:
#            template_choice:
#              - object_list
    Plant:
      Chiller:
        Base: *HVACTemplatePlantChiller
        ReplaceElements:
        AdditionalTemplateObjects:
          condenser_type:
            WaterCooled:
              HVACTemplate:Plant:CondenserWaterLoop:
                ConnectorPath: CondenserWaterLoop
                UniqueName: 'Main CndW'
      ChilledWaterLoop:
        Base: *HVACTemplatePlantChilledWaterLoop
      CondenserWaterLoop:
        Base: *HVACTemplatePlantCondenserWaterLoop
      Tower:
        Base: *HVACTemplatePlantTower