# Objects
OutdoorAir:NodeLists:
  BaseConfig: &OutdoorAirNodeListBase
    OutdoorAir:NodeList:
      Fields:
        - '{} Outside Air Inlet'
      Connectors:
        Air:
          Outlet: '{} Outside Air Inlet'

OutdoorAir:Mixers: # structure might be unnecessary but is being used for example
  CommonFields: &OutdoorAirMixersCommonFields
    name: '{} OA Mixing Box'
    mixed_air_node_name: '{} Mixed Air Outlet'
    outdoor_air_stream_node_name: '{} Outside Air Inlet' #will be overridden
    relief_air_stream_node_name: '{} Relief Air Outlet'
    return_air_stream_node_name: '{} Return Air Loop Inlet'
  CommonConnectors: &OutdoorAirMixersCommonConnectors
    Air:
      inlet: outdoor_air_stream_node_name
      Outlet: mixed_air_node_name
  BaseConfig: &OutdoorAirMixerBase
    OutdoorAir:Mixer:
      Fields:
        << : *OutdoorAirMixersCommonFields
      Connectors:
        << : *OutdoorAirMixersCommonConnectors

Coils:
  Cooling:
    Water:
      CommonFields: &CoilsCoolingCommonFields
        name: '{} Cooling Coil'
        air_inlet_node_name: '{} Cooling Coil Inlet'
        air_outlet_node_name: '{} Cooling Coil Outlet'
        water_inlet_node_name: '{} Cooling Coil Chw Inlet'
        water_outlet_node_name: '{} Cooling Coil Chw Outlet'
      CommonConnectors: &CoilsCoolingCommonConnectors
        Air:
          Inlet: air_inlet_node_name
          Outlet: air_outlet_node_name
        ChilledWater:
          Inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilsCoolingWaterBase
        Coil:Cooling:Water:
          Fields:
            << : *CoilsCoolingCommonFields
          Connectors:
            << : *CoilsCoolingCommonConnectors
      DetailedGeometry: &CoilsCoolingWaterDetailedGeometry
        Coil:Cooling:Water:DetailedGeometry:
          Fields:
            << : *CoilsCoolingCommonFields
          Connectors:
            << : *CoilsCoolingCommonConnectors
  Heating:
    CommonFields: &CoilsHeatingCommonFields
      name: '{} Heating Coil'
      air_inlet_node_name: '{} Heating Coil Inlet'
      air_outlet_node_name: '{} Heating Coil Outlet'
    CommonConnectors: &CoilsHeatingCommonConnectors
      Air:
        Inlet: air_inlet_node_name
        Outlet: air_outlet_node_name
    Electric:
      CommonFields:
      CommonConnectors:
      Base: &CoilsHeatingElectricBase
        Coil:Heating:Electric:
          Fields:
            <<: *CoilsHeatingCommonFields
          Connectors:
            <<: *CoilsHeatingCommonConnectors
    Water:
      CommonFields: &CoilsHeatingWaterCommonFields
        << : *CoilsHeatingCommonFields
        water_inlet_node_name: '{} Heating Coil Chw Inlet'
        water_outlet_node_name: '{} Heating Coil Chw Outlet'
      CommonConnectors: &CoilsHeatingWaterCommonConnectors
        << : *CoilsHeatingCommonConnectors
        HotWater:
          inlet: water_inlet_node_name
          Outlet: water_outlet_node_name
      Base: &CoilsHeatingWaterBase
        Coil:Heating:Water:
          Fields:
            <<: *CoilsHeatingWaterCommonFields
          Connectors:
            <<: *CoilsHeatingWaterCommonConnectors

# System Fans
Fan:
  CommonFields: &FanCommonFields
    name: '{} Supply Fan'
  CommonConnectors: &FanCommonConnectors
    Air:
      Inlet: air_inlet_node_name
      Outlet: air_outlet_node_name
  VariableVolume:
    Base: &FanVariableVolumeBase
      Fan:VariableVolume:
        Fields:
          << : *FanCommonFields
          air_inlet_node_name: '{} Supply Fan Inlet'
          air_outlet_node_name: '{} Supply Fan Outlet'
        Connectors:
          << : *FanCommonConnectors

# Basic Systems
SystemConfigOutdoorAirBase: &SystemConfigOutdoorAirBase
  - << : *OutdoorAirNodeListBase
  - << : *OutdoorAirMixerBase

# HVAC System Templates
HVACTemplate:System:VAV: &HVACTemplateSystemVAVBaseTemplate
  buildPath:
    - *SystemConfigOutdoorAirBase
    - *CoilsCoolingWaterBase
    - *CoilsHeatingWaterBase
    - *FanVariableVolumeBase
  Transitions:
    supply_fan_total_efficiency:
      Fan:VariableVolume: fan_total_efficiency
  Connectors:
    Supply: # we can easily get the outlet name from the last object in the buildPath so it's not referenced here
      Inlet:
        OutdoorAir:Mixer: return_air_stream_node_name
    Demand:
      Inlet: '{} Supply Path Inlet'
      Outlet: '{} Return Air Outlet'
  SetpointManagers:
    SetpointManager:MixedAir:
      name: '{} Cooling Coil Air Temp Manager'
      control_variable: 'Temperature'
      reference_setpoint_node_name:
        AirLoopHVAC: 'supply_side_outlet_node_names'
  Controllers:
    Controller:OutdoorAir:
      name: '{} OA Controller'
      revief_air_outlet_node_name:
        OutdoorAir:Mixer: relief_air_stream_node_name
      return_air_node_name:
        OutdoorAir:Mixer: return_air_stream_node_name

# Option trees
OptionTree:HVACTemplate:System:VAV:
  Base: *HVACTemplateSystemVAVBaseTemplate
  ReplaceElements:
    heating_coil_type: # assume base default is anything except None
      ReplaceRegex: '^Coil:Heating:*' # regular expression to find object in the buildPath
      ReplaceElement:
        None: None
        Electric:
          Object: *CoilsHeatingElectricBase # anchor/map reference to coil
          FieldNameReplacement: '{} Electric'
  InsertElements:
    preheat_coil_type:
      Location:
        BeforeObject: OutdoorAir:Mixer
      ObjectType:
        Electric:
          Object: *CoilsHeatingElectricBase
          FieldNameReplacement: '{} Preheat Electric'
  RemoveElements: # Not sure if this is needed but it's possible using list.pop()
  AddControllers: # objects to create new objects not in base list
    field_key_that_flags_controller:
      field_value: controller_object_to_be_merged
  AddSetpointManagers: # options to create new objects not in list
    preheat_coil_type:
      any: setpoint_manager_object_to_be_merged
