import unittest
from pathlib import Path

from argparse import Namespace
import tempfile
import json
from . import BaseTest
from src.main import main

test_dir = Path(__file__).parent.parent

minimum_objects_d = {
    "Building": {
        "Test Building": {}
    },
    "GlobalGeometryRules": {
        "GlobalGeometryRules 1": {
            "coordinate_system": "Relative",
            "starting_vertex_position": "UpperLeftCorner",
            "vertex_entry_direction": "Counterclockwise"
        }
    }
}

hot_water_loop = {
    "HVACTemplate:Plant:HotWaterLoop": {
        "Hot Water Loop": {
            "hot_water_design_setpoint": 82,
            "hot_water_plant_operation_scheme_type": "Default",
            "hot_water_pump_configuration": "ConstantFlow",
            "hot_water_pump_rated_head": 179352,
            "hot_water_reset_outdoor_dry_bulb_high": 10,
            "hot_water_reset_outdoor_dry_bulb_low": -6.7,
            "hot_water_setpoint_at_outdoor_dry_bulb_high": 65.6,
            "hot_water_setpoint_at_outdoor_dry_bulb_low": 82.2,
            "hot_water_setpoint_reset_type": "OutdoorAirTemperatureReset",
            "pump_control_type": "Intermittent"
        }
    }
}

chilled_water_objects = {
    "HVACTemplate:Plant:ChilledWaterLoop": {
        "Chilled Water Loop": {
            "chilled_water_design_setpoint": 7.22,
            "chilled_water_pump_configuration": "ConstantPrimaryNoSecondary",
            "chilled_water_reset_outdoor_dry_bulb_high": 26.7,
            "chilled_water_reset_outdoor_dry_bulb_low": 15.6,
            "chilled_water_setpoint_at_outdoor_dry_bulb_high": 6.7,
            "chilled_water_setpoint_at_outdoor_dry_bulb_low": 12.2,
            "chilled_water_setpoint_reset_type": "None",
            "chiller_plant_operation_scheme_type": "Default",
            "condenser_plant_operation_scheme_type": "Default",
            "condenser_water_design_setpoint": 29.4,
            "condenser_water_pump_rated_head": 179352,
            "minimum_outdoor_dry_bulb_temperature": 7.22,
            "primary_chilled_water_pump_rated_head": 179352,
            "pump_control_type": "Intermittent",
            "secondary_chilled_water_pump_rated_head": 179352
        }
    },
    "HVACTemplate:Plant:Chiller": {
        "Main Chiller": {
            "capacity": "Autosize",
            "chiller_type": "ElectricReciprocatingChiller",
            "condenser_type": "WaterCooled",
            "nominal_cop": 3.2,
            "priority": "1"
        }
    },
    "HVACTemplate:Plant:Tower": {
        "Main Tower": {
            "free_convection_capacity": "Autosize",
            "high_speed_fan_power": "Autosize",
            "high_speed_nominal_capacity": "Autosize",
            "low_speed_fan_power": "Autosize",
            "low_speed_nominal_capacity": "Autosize",
            "priority": "1",
            "tower_type": "SingleSpeed"
        }
    }
}


class TestUserWarnings(BaseTest, unittest.TestCase):
    """
    Test warnings generated by user behaviour
    """
    def setUp(self):
        return

    def tearDown(self):
        return

    def test_invalid_choice(self):
        # todo_eo: this only works if schema validation is turned on.  The point of turning it off is to speed up
        #  the process so no output in that case may be the only option
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:FanCoil": {
                        "FanCoil 1": {}
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Invalid choice in HVACTemplate:Zone:FanCoil .* '
                                                              r'is a required property')
        return

    def test_two_hot_water_loop_templates_with_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:HotWaterLoop": {
                        "Hot Water Loop": {
                            "hot_water_design_setpoint": 82,
                            "hot_water_plant_operation_scheme_type": "Default",
                            "hot_water_pump_configuration": "ConstantFlow",
                            "hot_water_pump_rated_head": 179352,
                            "hot_water_reset_outdoor_dry_bulb_high": 10,
                            "hot_water_reset_outdoor_dry_bulb_low": -6.7,
                            "hot_water_setpoint_at_outdoor_dry_bulb_high": 65.6,
                            "hot_water_setpoint_at_outdoor_dry_bulb_low": 82.2,
                            "hot_water_setpoint_reset_type": "OutdoorAirTemperatureReset",
                            "pump_control_type": "Intermittent"
                        },
                        "Hot Water Loop 2": {
                            "hot_water_design_setpoint": 82,
                            "hot_water_plant_operation_scheme_type": "Default",
                            "hot_water_pump_configuration": "ConstantFlow",
                            "hot_water_pump_rated_head": 179352,
                            "hot_water_reset_outdoor_dry_bulb_high": 10,
                            "hot_water_reset_outdoor_dry_bulb_low": -6.7,
                            "hot_water_setpoint_at_outdoor_dry_bulb_high": 65.6,
                            "hot_water_setpoint_at_outdoor_dry_bulb_low": 82.2,
                            "hot_water_setpoint_reset_type": "OutdoorAirTemperatureReset",
                            "pump_control_type": "Intermittent"
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Input file does not meet schema format')
        return

    def test_two_hot_water_loop_templates_no_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:HotWaterLoop": {
                        "Hot Water Loop": {
                            "hot_water_design_setpoint": 82,
                            "hot_water_plant_operation_scheme_type": "Default",
                            "hot_water_pump_configuration": "ConstantFlow",
                            "hot_water_pump_rated_head": 179352,
                            "hot_water_reset_outdoor_dry_bulb_high": 10,
                            "hot_water_reset_outdoor_dry_bulb_low": -6.7,
                            "hot_water_setpoint_at_outdoor_dry_bulb_high": 65.6,
                            "hot_water_setpoint_at_outdoor_dry_bulb_low": 82.2,
                            "hot_water_setpoint_reset_type": "OutdoorAirTemperatureReset",
                            "pump_control_type": "Intermittent"
                        },
                        "Hot Water Loop 2": {
                            "hot_water_design_setpoint": 82,
                            "hot_water_plant_operation_scheme_type": "Default",
                            "hot_water_pump_configuration": "ConstantFlow",
                            "hot_water_pump_rated_head": 179352,
                            "hot_water_reset_outdoor_dry_bulb_high": 10,
                            "hot_water_reset_outdoor_dry_bulb_low": -6.7,
                            "hot_water_setpoint_at_outdoor_dry_bulb_high": 65.6,
                            "hot_water_setpoint_at_outdoor_dry_bulb_low": 82.2,
                            "hot_water_setpoint_reset_type": "OutdoorAirTemperatureReset",
                            "pump_control_type": "Intermittent"
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=True
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Only one HVACTemplate:Plant:HotWaterLoop.*')
        return

    def test_two_chilled_water_loop_templates_with_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:ChilledWaterLoop": {
                        "Chilled Water Loop": {
                            "chilled_water_design_setpoint": 7.22,
                            "chilled_water_pump_configuration": "ConstantPrimaryNoSecondary",
                            "chilled_water_reset_outdoor_dry_bulb_high": 26.7,
                            "chilled_water_reset_outdoor_dry_bulb_low": 15.6,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_high": 6.7,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_low": 12.2,
                            "chilled_water_setpoint_reset_type": "None",
                            "chiller_plant_operation_scheme_type": "Default",
                            "condenser_plant_operation_scheme_type": "Default",
                            "condenser_water_design_setpoint": 29.4,
                            "condenser_water_pump_rated_head": 179352,
                            "minimum_outdoor_dry_bulb_temperature": 7.22,
                            "primary_chilled_water_pump_rated_head": 179352,
                            "pump_control_type": "Intermittent",
                            "secondary_chilled_water_pump_rated_head": 179352
                        },
                        "Chilled Water Loop 2": {
                            "chilled_water_design_setpoint": 7.22,
                            "chilled_water_pump_configuration": "ConstantPrimaryNoSecondary",
                            "chilled_water_reset_outdoor_dry_bulb_high": 26.7,
                            "chilled_water_reset_outdoor_dry_bulb_low": 15.6,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_high": 6.7,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_low": 12.2,
                            "chilled_water_setpoint_reset_type": "None",
                            "chiller_plant_operation_scheme_type": "Default",
                            "condenser_plant_operation_scheme_type": "Default",
                            "condenser_water_design_setpoint": 29.4,
                            "condenser_water_pump_rated_head": 179352,
                            "minimum_outdoor_dry_bulb_temperature": 7.22,
                            "primary_chilled_water_pump_rated_head": 179352,
                            "pump_control_type": "Intermittent",
                            "secondary_chilled_water_pump_rated_head": 179352
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Input file does not meet schema format')
        return

    def test_two_chilled_water_loop_templates_no_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:ChilledWaterLoop": {
                        "Chilled Water Loop": {
                            "chilled_water_design_setpoint": 7.22,
                            "chilled_water_pump_configuration": "ConstantPrimaryNoSecondary",
                            "chilled_water_reset_outdoor_dry_bulb_high": 26.7,
                            "chilled_water_reset_outdoor_dry_bulb_low": 15.6,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_high": 6.7,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_low": 12.2,
                            "chilled_water_setpoint_reset_type": "None",
                            "chiller_plant_operation_scheme_type": "Default",
                            "condenser_plant_operation_scheme_type": "Default",
                            "condenser_water_design_setpoint": 29.4,
                            "condenser_water_pump_rated_head": 179352,
                            "minimum_outdoor_dry_bulb_temperature": 7.22,
                            "primary_chilled_water_pump_rated_head": 179352,
                            "pump_control_type": "Intermittent",
                            "secondary_chilled_water_pump_rated_head": 179352
                        },
                        "Chilled Water Loop 2": {
                            "chilled_water_design_setpoint": 7.22,
                            "chilled_water_pump_configuration": "ConstantPrimaryNoSecondary",
                            "chilled_water_reset_outdoor_dry_bulb_high": 26.7,
                            "chilled_water_reset_outdoor_dry_bulb_low": 15.6,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_high": 6.7,
                            "chilled_water_setpoint_at_outdoor_dry_bulb_low": 12.2,
                            "chilled_water_setpoint_reset_type": "None",
                            "chiller_plant_operation_scheme_type": "Default",
                            "condenser_plant_operation_scheme_type": "Default",
                            "condenser_water_design_setpoint": 29.4,
                            "condenser_water_pump_rated_head": 179352,
                            "minimum_outdoor_dry_bulb_temperature": 7.22,
                            "primary_chilled_water_pump_rated_head": 179352,
                            "pump_control_type": "Intermittent",
                            "secondary_chilled_water_pump_rated_head": 179352
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=True
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Only one HVACTemplate:Plant:ChilledWaterLoop.*')
        self.assertRegex(output['outputPreProcessorMessage'], r'.*You must specify at least one.*')
        return

    def test_two_mixed_water_loop_templates_with_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:MixedWaterLoop": {
                        "Only Water Loop": {
                            "high_temperature_design_setpoint": 30,
                            "low_temperature_design_setpoint": 20,
                            "operation_scheme_type": "Default",
                            "pump_control_type": "Intermittent",
                            "water_pump_configuration": "ConstantFlow",
                            "water_pump_rated_head": 179352
                        },
                        "Only Water Loop 2": {
                            "high_temperature_design_setpoint": 30,
                            "low_temperature_design_setpoint": 20,
                            "operation_scheme_type": "Default",
                            "pump_control_type": "Intermittent",
                            "water_pump_configuration": "ConstantFlow",
                            "water_pump_rated_head": 179352
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Input file does not meet schema format')
        return

    def test_two_mixed_water_loop_templates_no_schema(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:MixedWaterLoop": {
                        "Only Water Loop": {
                            "high_temperature_design_setpoint": 30,
                            "low_temperature_design_setpoint": 20,
                            "operation_scheme_type": "Default",
                            "pump_control_type": "Intermittent",
                            "water_pump_configuration": "ConstantFlow",
                            "water_pump_rated_head": 179352
                        },
                        "Only Water Loop 2": {
                            "high_temperature_design_setpoint": 30,
                            "low_temperature_design_setpoint": 20,
                            "operation_scheme_type": "Default",
                            "pump_control_type": "Intermittent",
                            "water_pump_configuration": "ConstantFlow",
                            "water_pump_rated_head": 179352
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=True
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*Only one HVACTemplate:Plant:MixedWaterLoop.*')
        self.assertRegex(output['outputPreProcessorMessage'], r'.*You must specify at least one.*')
        return

    def test_zone_equipment_no_system(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:VAV": {
                        "VAV Zone 1": {
                            "zone_name": 'SPACE1-1',
                            'template_vav_system_name': 'Sys 1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Could not find air handler name referenced')
        return

    def test_baseboard_hot_water_no_supply_equipment(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:FanCoil": {
                        "FanCoil 1": {
                            "zone_name": 'SPACE1-1',
                            "baseboard_heating_type": 'HotWater'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'.*HVACTemplate:Plant:HotWaterLoop and a '
                                                              r'HVACTemplate:Plant:Boiler are needed.*')
        return

    def test_fan_coil_doas_with_constant_fan(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:FanCoil": {
                        "FanCoil 1": {
                            "zone_name": 'SPACE1-1',
                            "capacity_control_method": 'ConstantFanVariableFlow',
                            'dedicated_outdoor_air_system_name': 'DOAS'
                        }
                    },
                    'HVACTemplate:System:DedicatedOutdoorAir': {
                        'DOAS': {}
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Capacity Control Method is')
        return

    def test_ideal_load_flow_heat_limit_flow(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "heating_limit": 'LimitFlowRate'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Limit field is LimitFlowRate but the '
                                                              r'Maximum Heating Air Flow Rate field')
        return

    def test_ideal_load_flow_cool_limit_flow(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "cooling_limit": 'LimitFlowRate'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Limit field is LimitFlowRate but the '
                                                              r'Maximum Cooling Air Flow Rate field')
        return

    def test_ideal_load_flow_heat_limit_capacity(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "heating_limit": 'LimitCapacity'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Limit field is LimitCapacity but the '
                                                              r'Maximum Sensible Heating Capacity field')
        return

    def test_ideal_load_flow_cool_limit_capacity(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "cooling_limit": 'LimitCapacity'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Cooling Limit field is LimitCapacity but the '
                                                              r'Maximum Total Cooling Capacity field')
        return

    def test_ideal_load_flow_heat_limit_flow_and_capacity(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "heating_limit": 'LimitFlowRateAndCapacity'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Limit field is LimitFlowRateAndCapacity but '
                                                              r'the Maximum Heating Air Flow Rate field is blank and '
                                                              r'the Maximum Sensible Heating Capacity field is blank.')
        return

    def test_ideal_load_flow_cool_limit_flow_and_capacity(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:IdealLoadsAirSystem": {
                        "IL 1": {
                            "zone_name": 'SPACE1-1',
                            "cooling_limit": 'LimitFlowRateAndCapacity'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Cooling Limit field is LimitFlowRateAndCapacity but '
                                                              r'the Maximum Cooling Air Flow Rate field is blank and '
                                                              r'the Maximum Total Cooling Capacity field is blank.')
        return

    def test_vav_heating_cooling_setpoint_mismatch(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:System:VAV": {
                        "VAV Sys 1": {
                            'cooling_coil_design_setpoint': 12,
                            "heating_coil_type": 'Electric',
                            'heating_coil_design_setpoint': 15
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Coil Design Setpoint is greater than '
                                                              r'the Cooling Coil Design Setpoint.')
        return

    def test_cav_heating_cooling_setpoint_mismatch(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:ConstantVolume": {
                        'CV Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'cooling_coil_design_setpoint': 12,
                            "heating_coil_type": 'Electric',
                            'heating_coil_design_setpoint': 15
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Coil Design Setpoint is greater than '
                                                              r'the Cooling Coil Design Setpoint.')
        return

    def test_vav_preheating_cooling_setpoint_mismatch(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:VAV": {
                        'VAV Zone 1': {
                            'template_vav_system_name': 'VAV Sys 1',
                            'zone_name': 'SPACE1-1'
                        }
                    },
                    "HVACTemplate:System:VAV": {
                        "VAV Sys 1": {
                            'cooling_coil_design_setpoint': 12,
                            'preheat_coil_type': 'Electric',
                            'preheat_coil_design_setpoint': 15
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Preheat Coil Design Setpoint is greater than '
                                                              r'the Cooling Coil Design Setpoint')
        return

    def test_cav_preheating_cooling_setpoint_mismatch(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:ConstantVolume": {
                        'CV Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'cooling_coil_design_setpoint': 12,
                            'preheat_coil_type': 'Electric',
                            'preheat_coil_design_setpoint': 15
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Preheat Coil Design Setpoint is greater than '
                                                              r'the Cooling Coil Design Setpoint')
        return

    def test_vav_preheating_override_setpoint(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:System:VAV": {
                        "VAV Sys 1": {
                            'heating_coil_design_setpoint': 15,
                            'preheat_coil_type': 'Electric',
                            'preheat_coil_design_setpoint': 7
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Coil Design Setpoint is greater than the '
                                                              r'Preheat Coil Design Setpoint,')
        return

    def test_cav_preheating_override_setpoint(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:ConstantVolume": {
                        'CV Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'heating_coil_design_setpoint': 15,
                            'preheat_coil_type': 'Electric',
                            'preheat_coil_design_setpoint': 7
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Heating Coil Design Setpoint is greater than the '
                                                              r'Preheat Coil Design Setpoint,')
        return

    def test_vav_preheating_override_no_preheat_coil_setpoint(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:VAV": {
                        'VAV Zone 1': {
                            'template_vav_system_name': 'VAV Sys 1',
                            'zone_name': 'SPACE1-1'
                        }
                    },
                    "HVACTemplate:System:VAV": {
                        "VAV Sys 1": {
                            'preheat_coil_type': 'None',
                            'preheat_coil_design_setpoint': 7
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'there is no Heating Coil and no Preheat Coil.')
        return

    def test_unitary_control_zone_no_template(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    'HVACTemplate:Zone:Unitary': {
                        'Uniitary Zone 1': {
                            'template_unitary_system_name': 'Unitary Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:Unitary": {
                        "Unitary Sys 1": {
                            'heating_coil_type': 'Electric',
                            'control_zone_or_thermostat_location_name': 'SPACE1-1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'for the field control_zone_or_thermostat_location_name '
                                                              r'could not find a matching')
        return

    def test_cav_cooling_control_zone_no_template(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    'HVACTemplate:Zone:ConstantVolume': {
                        'CV Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'heating_coil_type': 'Electric',
                            'cooling_coil_control_zone_name': 'SPACE1-1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'for the field cooling_coil_control_zone_name '
                                                              r'could not find a matching')
        return

    def test_cav_heating_control_zone_no_template(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    'HVACTemplate:Zone:ConstantVolume': {
                        'CV Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'heating_coil_type': 'Electric',
                            'heating_coil_control_zone_name': 'SPACE1-1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'for the field heating_coil_control_zone_name '
                                                              r'could not find a matching')
        return

    def test_vrf_master_thermostat_no_template(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    'HVACTemplate:Zone:VRF': {
                        'VRF Zone 1': {
                            'template_vrf_system_name': 'VRF Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:VRF": {
                        "VRF Sys 1": {
                            'master_thermostat_priority_control_type': 'MasterThermostatPriority',
                            'zone_name_for_master_thermostat_location': 'SPACE1-1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'field Zone Name for Master Thermostat Location could '
                                                              r'not find a matching')
        return

    def test_vrf_master_thermostat_scheduled_no_schedule(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    'HVACTemplate:Zone:VRF': {
                        'VRF Zone 1': {
                            'template_vrf_system_name': 'VRF Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:VRF": {
                        "VRF Sys 1": {
                            'master_thermostat_priority_control_type': 'Scheduled',
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Priority Control Type = Scheduled, but the Thermostat '
                                                              r'Priority Schedule Name')
        return

    def test_unitary_control_zone_bad_template(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Zone:Unitary": {
                        'Unitary Zone 1': {
                            'template_unitary_system_name': 'Unitary Sys 1',
                            'zone_name': 'SPACE2-1'
                        }
                    },
                    "HVACTemplate:System:Unitary": {
                        "Unitary Sys 1": {
                            'heating_coil_type': 'Electric',
                            'control_zone_or_thermostat_location_name': 'SPACE1-1'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the field control_zone_or_thermostat_location_name '
                                                              r'could not find a matching HVACTemplate:Zone:Unitary')
        return

    def test_night_cycle_control_zone(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    "HVACTemplate:Thermostat": {
                        "All Zones": {
                            "cooling_setpoint_schedule_name": "Clg-SetP-Sch",
                            "heating_setpoint_schedule_name": "Htg-SetP-Sch"
                        }
                    },
                    "HVACTemplate:Zone:ConstantVolume": {
                        'Unitary Zone 1': {
                            'template_constant_volume_system_name': 'CV Sys 1',
                            "template_thermostat_name": "All Zones",
                            'zone_name': 'SPACE1-1'
                        }
                    },
                    "HVACTemplate:System:ConstantVolume": {
                        "CV Sys 1": {
                            'cooling_coil_type': 'ChilledWater',
                            'cooling_coil_design_setpoint': 12.8,
                            'cooling_coil_setpoint_control_type': 'FixedSetpoint',
                            'heating_coil_type': 'Electric',
                            'heating_coil_setpoint_control_type': 'FixedSetpoint',
                            'heating_coil_design_setpoint': 15,
                            'night_cycle_control': 'CycleOnControlZone'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'A zone name must be specified when Night Cycle Control')
        return

    def test_unitary_system_dx_cooling_coil_sensible_heat_ratio(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    "HVACTemplate:Zone:Unitary": {
                        'Unitary Zone 1': {
                            'template_unitary_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE1-1'
                        }
                    },
                    "HVACTemplate:System:UnitarySystem": {
                        "CV Sys 1": {
                            'dx_cooling_coil_gross_rated_sensible_heat_ratio': 0.66
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'the Cooling Coil Rated Capacity is autosized, so the '
                                                              r'Cooling Coil Gross Rated Sensible Heat Ratio')
        return

    def test_unitary_system_dx_cooling_coil_total_capacity(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    "HVACTemplate:Zone:Unitary": {
                        'Unitary Zone 1': {
                            'template_unitary_system_name': 'CV Sys 1',
                            'zone_name': 'SPACE1-1'
                        }
                    },
                    "HVACTemplate:System:UnitarySystem": {
                        "CV Sys 1": {
                            'dx_cooling_coil_gross_rated_total_capacity': 1000
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'he Cooling Coil Rated Capacity will not be used when '
                                                              r'the Cooling Coil Gross Rated ')
        return

    def test_system_with_no_zones(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    'HVACTemplate:Zone:Unitary': {
                        'Zone 1': {
                            'template_unitary_system_name': 'CV Sys 2',
                            'zone_name': 'SPACE1-1'}},
                    "HVACTemplate:System:UnitarySystem": {
                        "CV Sys 1": {
                            'dx_cooling_coil_gross_rated_total_capacity': 1000
                        },
                        "CV Sys 2": {
                            'dx_cooling_coil_gross_rated_total_capacity': 1000
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Did not find any HVACTemplate:Zone objects connected to')
        return

    def test_tower_not_all_autosize(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    'HVACTemplate:Plant:Tower': {
                        'Tower 1': {
                            'tower_type': 'SingleSpeed',
                            'high_speed_nominal_capacity': 'Autosize',
                            'free_convection_capacity': 200
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
            self.assertRegex(output['outputPreProcessorMessage'], r'For a SingleSpeed tower the high speed capacity and '
                                                                  r'free convection capacity both need to be specified '
                                                                  r'or set to autosize')
            return

    def test_object_reference_boiler_no_type(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    **chilled_water_objects,
                    "HVACTemplate:Plant:Boiler:ObjectReference": {
                        "OR 1": {
                            'boiler_name': 'Main Boiler',
                            'boiler_object_type': 'Boiler:HotWater'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'n HVACTemplate:Plant:Boiler:ObjectReference \(OR 1\) '
                                                              r'Referenced boiler not found')
        return

    def test_object_reference_boiler_wrong_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Boiler:HotWater": {
                        'Main Boiler': {
                            'fuel_type': 'Coal',
                            'nominal_thermal_efficiency': 0.8,
                            'boiler_water_inlet_node_name': 'HW In',
                            'boiler_water_outlet_node_name': 'HW Out'
                        }
                    },
                    "HVACTemplate:Plant:Boiler:ObjectReference": {
                        "OR 1": {
                            'boiler_name': 'Bad Boiler',
                            'boiler_object_type': 'Boiler:HotWater'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'HVACTemplate:Plant:Boiler:ObjectReference \(OR 1\) '
                                                              r'Referenced boiler not found')
        return

    def test_object_reference_boiler_no_inlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Boiler:HotWater": {
                        'Main Boiler': {
                            'fuel_type': 'Coal',
                            'nominal_thermal_efficiency': 0.8,
                            'boiler_water_inlet_node_name': 'None',
                            'boiler_water_outlet_node_name': 'HW Out'
                        }
                    },
                    "HVACTemplate:Plant:Boiler:ObjectReference": {
                        "OR 1": {
                            'boiler_name': 'Main Boiler',
                            'boiler_object_type': 'Boiler:HotWater'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank Inlet Node Name found in referenced boiler: ')
        return

    def test_object_reference_boiler_no_outlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Boiler:HotWater": {
                        'Main Boiler': {
                            'fuel_type': 'Coal',
                            'nominal_thermal_efficiency': 0.8,
                            'boiler_water_inlet_node_name': 'HW In',
                            'boiler_water_outlet_node_name': ''
                        }
                    },
                    "HVACTemplate:Plant:Boiler:ObjectReference": {
                        "OR 1": {
                            'boiler_name': 'Main Boiler',
                            'boiler_object_type': 'Boiler:HotWater'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank Outlet Node Name found in referenced boiler: ')
        return

    def test_hot_water_loop_no_equipment(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:HotWaterLoop": {
                        "HWL 1": {

                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'There is no demand\-side equipment connected to this '
                                                              r'loop\. There is no supply\-side equipment serving this '
                                                              r'loop\.')
        return

    def test_object_reference_chiller_no_type(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'n HVACTemplate:Plant:Chiller:ObjectReference \(OR 1\) '
                                                              r'Referenced chiller not found')
        return

    def test_object_reference_chiller_wrong_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': 'CHW In',
                            'chilled_water_outlet_node_name': 'CHW Out'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Bad Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'HVACTemplate:Plant:Chiller:ObjectReference \(OR 1\) '
                                                              r'Referenced chiller not found')
        return

    def test_object_reference_chiller_no_chw_inlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': '',
                            'chilled_water_outlet_node_name': 'CHW Out'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank chilled water Inlet Node Name found in '
                                                              r'referenced chiller: ')
        return

    def test_object_reference_chiller_no_chw_outlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': 'CHW In',
                            'chilled_water_outlet_node_name': 'None'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank chilled water Outlet Node Name found in '
                                                              r'referenced chiller: ')
        return

    def test_object_reference_chiller_no_cw_inlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': 'CHW In',
                            'chilled_water_outlet_node_name': 'CHW Out',
                            'condenser_outlet_node_name': 'CW Out'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank condenser water Inlet Node Name')
        return

    def test_object_reference_chiller_no_cw_outlet_name(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': 'CHW In',
                            'chilled_water_outlet_node_name': 'CHW Out',
                            'condenser_inlet_node_name': 'CW In'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertRegex(output['outputPreProcessorMessage'], r'Blank condenser water Outlet Node Name')
        return

    def test_object_reference_chiller_air_cooled(self):
        with tempfile.NamedTemporaryFile(suffix='.epJSON', mode='w') as temp_file:
            json.dump(
                {
                    **minimum_objects_d,
                    "Chiller:Electric:EIR": {
                        'Main Chiller': {
                            'reference_capacity': 'Autosize',
                            'reference_cop': 6.1,
                            'cooling_capacity_function_of_temperature_curve_name': 'Main Chiller RecipCapFT',
                            'electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name': 'Main Chiller RecipEIRFPLR',
                            'electric_input_to_cooling_output_ratio_function_of_temperature_curve_name': 'Main Chiller RecipEIRFT',
                            'chilled_water_inlet_node_name': 'CHW In',
                            'chilled_water_outlet_node_name': 'CHW Out',
                            'condenser_type': 'AirCooled'
                        }
                    },
                    "HVACTemplate:Plant:Chiller:ObjectReference": {
                        "OR 1": {
                            'chiller_name': 'Main Chiller',
                            'chiller_object_type': 'Chiller:Electric:EIR'
                        }
                    }
                },
                temp_file)
            temp_file.seek(0)
            output = main(
                Namespace(
                    file=temp_file.name,
                    no_schema=False
                )
            )
        self.assertNotRegex(output['outputPreProcessorMessage'], r'Blank condenser water Inlet Node Name')
        return
